// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_COMPANY "Unity Technologies"
#define UNITY_COPYRIGHT "(c) 2005-2024 Unity Technologies. All rights reserved."
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2023
#define UNITY_VERSION_MAJ 2
#define UNITY_VERSION_MIN 10
#define UNITY_IS_BETA 0
#define UNITY_VERSION_UNDER_HASH "2023.2.10f1_316c1fd686f6"
#define UNITY_VERSION_PARENS_HASH "2023.2.10f1 (316c1fd686f6)"
#define UNITY_VERSION_BLD 3238943
#define UNITY_VERSION_WIN "2023.2.10.3238943"
